python3 ../scripts/stat.py -n 10 -c "likwid-perfctr -g MEM -C 0 -m ./matmul -d 20"
python3 ../scripts/stat.py -n 10 -c "likwid-perfctr -g MEM -C 0 -m ./matmul -d 50"
python3 ../scripts/stat.py -n 10 -c "likwid-perfctr -g MEM -C 0 -m ./matmul -d 100"
python3 ../scripts/stat.py -n 10 -c "likwid-perfctr -g MEM -C 0 -m ./matmul -d 200"
python3 ../scripts/stat.py -n 10 -c "likwid-perfctr -g MEM -C 0 -m ./matmul -d 500"
python3 ../scripts/stat.py -n 10 -c "likwid-perfctr -g MEM -C 0 -m ./matmul -d 1000"
python3 ../scripts/stat.py -n 10 -c "likwid-perfctr -g MEM -C 0 -m ./matmul -d 2000"
